{% set version = "0.2.18" %}

package:
  name: patiencediff
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/patiencediff/patiencediff-{{ version }}.tar.gz
  sha256: a678d8252bfb060f1f280fd32d47d917d323e93e1a94ff4ddaaba693a6f66aad

build:
  number: 0
  script_env:
    - CFLAGS="-Wno-int-conversion"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - patiencediff
  requires:
    - pip
    - python

about:
  home: https://github.com/breezy-team/patiencediff
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Python implementation of the patiencediff algorithm

extra:
  recipe-maintainers:
    - danielnachun
