{% set version = "0.2.15" %}

package:
  name: patiencediff
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/patiencediff/patiencediff-{{ version }}.tar.gz
  sha256: d00911efd32e3bc886c222c3a650291440313ee94ac857031da6cc3be7935204

build:
  number: 0
  script_env:
    - CFLAGS="-Wno-int-conversion"
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - pip check
  imports:
    - patiencediff
  requires:
    - pip
    - python

about:
  home: https://github.com/breezy-team/patiencediff
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Python implementation of the patiencediff algorithm

extra:
  recipe-maintainers:
    - danielnachun
